server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # pour eureka
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
endpoints:  # pour exposer l'api de shutdown pour eureka
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true # les services se reconnaissent par ip car pas de dns
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# pour le eureka dashboard
info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"

logging:
  level:
    org.springframework.cloud.netflix.eureka: debug