spring:
  config:
    activate:
      on-profile: "qa"


build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs QA"
  contactDetails:
    name: "John Doe - QA Developer "
    email: "johnqa@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
